name: Security and Quality Checks

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  schedule:
    - cron: '0 0 * * 0'  # Fixed cron syntax

jobs:
  security-scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [authentication, e-commerce, learning-management-system]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'  # Specify your Go version

      - name: Check if service changed
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            service:
              - '${{ matrix.service }}/**'

      - name: Cache Go Modules
        if: steps.changes.outputs.service == 'true' || github.event_name == 'schedule'
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.service }}-${{ hashFiles(format('{0}/go.sum', matrix.service)) }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.service }}-

      - name: Initialize Go Module (if needed)
        if: steps.changes.outputs.service == 'true' || github.event_name == 'schedule'
        working-directory: ./${{ matrix.service }}
        run: |
          if [ ! -f go.mod ]; then
            go mod init github.com/content-management-system/backend/${{ matrix.service }}
          fi

      - name: Download Dependencies
        if: steps.changes.outputs.service == 'true' || github.event_name == 'schedule'
        working-directory: ./${{ matrix.service }}
        run: |
          go mod tidy
          go mod download
          go mod verify

      - name: Build to verify dependencies
        if: steps.changes.outputs.service == 'true' || github.event_name == 'schedule'
        working-directory: ./${{ matrix.service }}
        run: |
          go build -v ./...

      - name: Run Gosec Security Scanner
        if: steps.changes.outputs.service == 'true' || github.event_name == 'schedule'
        uses: securego/gosec@master
        with:
          args: './${{ matrix.service }}/...'

      - name: Run Trivy vulnerability scanner
        if: steps.changes.outputs.service == 'true' || github.event_name == 'schedule'
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: './${{ matrix.service }}'